services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: jz
      POSTGRES_PASSWORD: cs490
      POSTGRES_DB: cs_office_hours
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "5002:5002"
    environment:
      DATABASE_URL: "postgresql://jz:cs490@db:5432/cs_office_hours"
      FLASK_SECRET_KEY: "jwNn1qboghipr7NtvwMLkz42ILKj8aN0"
      YALIES_API_KEY: Bearer gZTCZ60PS3erBGaA8tYE_5KDdc9l_aDqbSTypkqf7nZvjjc6r4Jj1Q
      YALIES_API_URL: "https://api.yalies.io/v2/people"
      FRONTEND_URL: "http://localhost:3000"
      BASE_URL: "http://web:5002"
      SUPERUSER_NETIDS: "ap2626,jz775"
    depends_on:
      - db
    command: python backend/app.py 
volumes:
  pgdata:
