"""empty message

Revision ID: 0e2836b1f08a
Revises: 1bad690b2df8
Create Date: 2025-04-01 15:37:53.720647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2836b1f08a'
down_revision = '1bad690b2df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.drop_column('position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
