"""empty message

Revision ID: 1bad690b2df8
Revises: aa9c245c7201
Create Date: 2025-03-30 22:04:29.527539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bad690b2df8'
down_revision = 'aa9c245c7201'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', postgresql.ENUM('in-person', 'virtual', name='office_hours_mode_enum'), server_default='in-person', nullable=False))
 
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
