"""Indexes + Timezones

Revision ID: 9c14e4ce6a88
Revises: 9c1a04ba27eb
Create Date: 2025-04-12 15:00:21.008421

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c14e4ce6a88'
down_revision = '9c1a04ba27eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.alter_column('time_entered',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('time_started',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('time_finished',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_index('idx_queue_entry_time_entered', ['time_entered'], unique=False)
        batch_op.create_index('idx_queue_entry_time_finished', ['time_finished'], unique=False)
        batch_op.create_index('idx_queue_entry_time_started', ['time_started'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entry', schema=None) as batch_op:
        batch_op.drop_index('idx_queue_entry_time_started')
        batch_op.drop_index('idx_queue_entry_time_finished')
        batch_op.drop_index('idx_queue_entry_time_entered')
        batch_op.alter_column('time_finished',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('time_started',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('time_entered',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
