"""Make course enrollment and staff size optional

Revision ID: aa9c245c7201
Revises: 
Create Date: 2025-03-29 21:47:33.441920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9c245c7201'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        pass  # Skipping 'unique_admin_course' since it already exists

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('enrollment_size',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('course_staff_size',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        pass  # Skipping 'unique_student_course' if it already exists

    with op.batch_alter_table('ula', schema=None) as batch_op:
        pass  # Skipping 'unique_ula_course' if it already exists

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ula', schema=None) as batch_op:
        batch_op.drop_constraint('unique_ula_course', type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_course', type_='unique')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_staff_size',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('enrollment_size',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('unique_admin_course', type_='unique')

    # ### end Alembic commands ###
