"""Add calendar_link to Course

Revision ID: af35777029cf
Revises: 0e2836b1f08a
Create Date: 2025-04-04 03:28:31.124874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af35777029cf'
down_revision = '0e2836b1f08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calendar_link', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ula', schema=None) as batch_op:
        batch_op.drop_constraint('unique_ula_course', type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_course', type_='unique')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('calendar_link')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('unique_admin_course', type_='unique')

    # ### end Alembic commands ###
