"""empty message

Revision ID: d68c71acbf0d
Revises: 1bad690b2df8
Create Date: 2025-03-30 22:43:59.810687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd68c71acbf0d'
down_revision = '1bad690b2df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_admin_course', ['net_id', 'course_id'])

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_student_course', ['net_id', 'course_id'])

    with op.batch_alter_table('ula', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_ula_course', ['net_id', 'course_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ula', schema=None) as batch_op:
        batch_op.drop_constraint('unique_ula_course', type_='unique')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint('unique_student_course', type_='unique')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('unique_admin_course', type_='unique')

    # ### end Alembic commands ###
